### ISSUE TITLE
Compilation failure with HDF5 v1.12

### ISSUE THREAD

**Issue by jwise77** [enzo-project/enzo-dev#143]
Reported on the mailing list by Ruoyi Yin
![photo](https://user-images.githubusercontent.com/12664560/78898342-a224b900-7a41-11ea-8c69-d2fe11c330c1.png)

**Comment by michaelkuhn** [comment]
I just ran into the same problem. Does #158 solve it for you?

**Comment by jwise77** [comment]
Fixed by #158
