### ISSUE TITLE
Problems to build enzo

### ISSUE THREAD

**Issue by Jessica-Lopez** [enzo-project/enzo-dev#163]
Hello!
I've installed grackle successfuly. When I try to build enzo, once  the path to grackle and hdf5 since yt were written,  I got this error message:

hydro_rk/Grid_GalaxyDiskInitializeGrid.C:317:11: error: ‘kpc_cm’ was not declared in this scope
  317 |       R_D/kpc_cm, DiskTemperature[0], h_0/kpc_cm, rho_0, c_s/1e5, Sigma_0/SolarMass*pc_cm*pc_cm);
      |           ^~~~~~
hydro_rk/Grid_GalaxyDiskInitializeGrid.C:317:85: error: ‘pc_cm’ was not declared in this scope
  317 |       R_D/kpc_cm, DiskTemperature[0], h_0/kpc_cm, rho_0, c_s/1e5, Sigma_0/SolarMass*pc_cm*pc_cm);
      |                                                                                     ^~~~~

make: *** [Makefile:275: hydro_rk/Grid_GalaxyDiskInitializeGrid.o] Error 1
...

I'm using the same path to hdf5 in both, grackle and enzo. Also I'm taking the Make-machine-linux-gnu.

Does someone can help me?

**Comment by clairekope** [comment]
Stale: Compiler error does not affect current version
