### ISSUE TITLE
Hypre library location changed - breaking tests

### ISSUE THREAD

**Issue by gregbryan** [enzo-project/enzo-dev#169]
It appears that Hypre, which we downloaded directly (from https://computation.llnl.gov/projects/hypre-scalable-linear-solvers-multigrid-methods/download/$HYPRE.tar.gz) is no longer available from that location and now needs to be built directly from the github repo (see instructions [here](https://github.com/hypre-space/hypre/blob/master/INSTALL.md)).  This is breaking some CIRCLECI tests (that don't have cached versions of hypre).

**Comment by jwise77** [comment]
Addressed in #170
