### ISSUE TITLE
Incorrect particle mass assigned in nested grid simulations with MUSIC ICs

### ISSUE THREAD

**Issue by mihirskulkarni** [enzo-project/enzo-dev#219]
Hello,

I found this issue while working with @gregbryan on a nested-grid cosmological simulation (2 h-1 Mpc with 128^3 root grid and 4 nested refinements in the zoomed region) using the initial conditions from MUSIC starting at z = 200. This corresponds to the dark matter particle mass of ~ 100 Msun in the innermost refined regions and DM particles with masses higher by a factor of 8 in the consecutive outer regions. I loaded a snapshot generated at z = 200 (immediately after starting the run), selected a region with bounds given by CosmologySimulationGridLeftEdge[4] and CosmologySimulationGridRightEdge[4] in the parameter file and looked at all the dark matter particles in it. This included most particles with mass ~ 100 Msun, a few with mass ~ 800 Msun, and surprisingly a few particles with mass ~ 6400 Msun that should not be there in the inner-most nested region. These ~6400 Msun DM particles were on a planar structure and led to an artificial gas collapse much earlier (at z = 50-70) than expected.

I believe this is caused by the lines 1449-1455 in Grid_NestedCosmologySimulationInitializeGrid.C.
```
      int NumberOfActiveCells = (GridEndIndex[0]-GridStartIndex[0]+1)*
        (GridEndIndex[1]-GridStartIndex[1]+1)*
        (GridEndIndex[2]-GridStartIndex[2]+1);
      if (NumberOfParticles*8 == NumberOfActiveCells)
        UniformParticleMass *= 8;
      if (NumberOfParticles == NumberOfActiveCells*8)
        UniformParticleMass /= 8;
```
which is multiplying the mass of particles on a particular grid by a factor of 8. To verify this, I changed this multiplicative factor to 3 instead of 8 in Grid_NestedCosmologySimulationInitializeGrid.C and reran and the innermost nested region ended with particles of mass ~ 2400 Msun.  I also did a run where I set `CosmologySimulationManuallySetParticleMassRatio` to 1 in the parameter file, so that this segment of code is ignored and the innermost nested region only had DM particles of mass 100 and 800 Msun and not 6400 Msun and it did not lead to an artificial collapse. 

I am a bit unsure about where the above snippet of code is used, but if it is removed, it will solve this problem. I can submit a pull request to do it.

Note: This problem occurred for multiple, but not all nested zoom simulations I performed. It also depends on the number of cores used. In this particular case, it happened only when I used 120 cores (5 nodes with 24 cores each), but not for the runs with fewer nodes used.

**Comment by jwise77** [comment]
I looked back at the history of this code, and it's been in there since 2009.  So that means it was used exclusively with `inits` initial conditions and not MUSIC.  But I don't know why this adjustment is necessary because all of the particles should have the same "mass" (i.e. density).  I've never run into this problem because I guess I've never had a zoom-in simulation with exactly these conditions.

I'd be in favor of removing this code segment, especially since it's causing trouble and that its purpose isn't clear.

**Comment by jwise77** [comment]
Actually I can guess why this was included.  I tracked down that this code wasn't present in the Stanford and Columbia versions of Enzo before the "week of code" merger in 2009.  At the same time, there was a student (no names) not in these groups who was experimenting using 8 particles per cell at initialization to improve mass resolution.  I can see how this code would correct the particle mass from `inits` if there were 8x the particles than cell count.

**Comment by gregbryan** [comment]
Yes, I agree with that origin, and that it is vistigial.
