### ISSUE TITLE
GPL violation in use of mercurial

### ISSUE THREAD

**Issue by brittonsmith** [enzo-project/enzo-dev#35]
**[Original report](https://bitbucket.org/enzo/enzo-dev/issue/35) by Nathan Goldbaum (Bitbucket: [ngoldbaum](https://bitbucket.org/ngoldbaum), GitHub: [ngoldbaum](https://github.com/ngoldbaum)).**

----------------------------------------

Currently Enzo's build system directly imports mercurial:

https://bitbucket.org/enzo/enzo-dev/src/240af05dd312d4d34a13cd6544f0ef63efbfdf77/src/enzo/create_config_info.py?at=week-of-code&fileviewer=file-view-default#create_config_info.py-19

Since Enzo is BSD-licensed, this is not allowed because directly importing mercurial implies that the python code that imports it must be GPL licensed. See https://www.mercurial-scm.org/wiki/MercurialApi for more details.

Instead, we should be talking to mercurial over the python-hglib command server. This will also allow us to support python installations based on python3, since python-hglib is available under python3.

**Comment by bwoshea** [comment]
@brittonsmith since we've moved to GitHub, this is no longer a bug, correct?

**Comment by jwise77** [comment]
Correct! I'm going to close this issue.
