### ISSUE TITLE
create_config_info.py SyntaxError

### ISSUE THREAD

**Issue by brittonsmith** [enzo-project/enzo-dev#41]
**[Original report](https://bitbucket.org/enzo/enzo-dev/issue/41) by yoshiki takahashi (Bitbucket: [yoshiki-takahashi](https://bitbucket.org/yoshiki-takahashi), GitHub: [yoshiki-takahashi](https://github.com/yoshiki-takahashi)).**

----------------------------------------

line 22,36
SyntaxError: Missing parentheses in call to 'print'. 
so change print( "WARNING: could not get version information.  Please install mercurial.")

**Comment by bwoshea** [comment]
I believe this is no longer used, since we use Git.  Is that correct, @brittonsmith?

**Comment by brittonsmith** [comment]
Yes, `create_config_info.py` is no longer called as of PR #52.
