### ISSUE TITLE
Consistent definition of physical constants

### ISSUE THREAD

**Issue by brittonsmith** [enzo-project/enzo-dev#43]
**[Original report](https://bitbucket.org/enzo/enzo-dev/issue/43) by Andrew Emerick (Bitbucket: [aemerick](https://bitbucket.org/aemerick), GitHub: [aemerick](https://github.com/aemerick)).**

----------------------------------------

Hi everyone,

One thing that has always bothered me are the separate definitions for solar mass throughout the code. This is ``1.989e33`` in many places, but is defined in ``physical_constants.h`` as ``SolarMass = 1.9891e33``. 

I would assume there may be similar inconsistencies with other physical constants. Should we push to have everything uniformly defined as in ``physical_constants.h``? If so, I can go through the code and replace all locally defined physical constants with the constants defined in ``physical_constants.h``. 

I wouldn't be surprised if this leads to large enough changes to answers to fail the test-suite.

**Comment by bwoshea** [comment]
@aemerick would you say that this issue has been closed?
