### ISSUE TITLE
Updating IO routines to be compatible with latest HDF5 versions

### ISSUE THREAD

**Issue by brittonsmith** [enzo-project/enzo-dev#46]
**[Original report](https://bitbucket.org/enzo/enzo-dev/issue/46) by Daegene Koh (Bitbucket: [dkoh](https://bitbucket.org/dkoh), GitHub: [dkoh](https://github.com/dkoh)).**

----------------------------------------

Currently Enzo can support up to HDF5 1.8. while 1.10 breaks it.

There are also concerns with the future roadmap of HDF5 and keeping up with the various changes that are coming. 

This could be resolved by simply updating Read/Write routines or perhaps reworking them altogether.

**Comment by jwise77** [comment]
Addressed in BB PR371
