### ISSUE TITLE
[JOSS REVIEW] LICENSE

### ISSUE THREAD

**Issue by zingale** [enzo-project/enzo-dev#94]
The license is University of Illinois/NCSA Open Source License until 2000 and UC BSD from 2000-2008.  Should we assume that that license remains in effect today?  Should the year be extended?

**Comment by zingale** [comment]
Somewhat related, the docs are copyright 2012:

https://enzo.readthedocs.io/en/enzo-2.6/user_guide/bootcamp.html

(see the footer).  Should that be updated too?

**Comment by zingale** [comment]
JOSS review: https://github.com/openjournals/joss-reviews/issues/1636

**Comment by bwoshea** [comment]
This is addressed in PR #113  @zingale

**Comment by zingale** [comment]
great.  Thanks!
