### ISSUE TITLE
[JOSS REVIEW] documentation link in README.md broken

### ISSUE THREAD

**Issue by zingale** [enzo-project/enzo-dev#97]
The `README.md` lists:

 http://enzo-project.org/docs/2.6/

for the docs, but this link is broken and gives a 404 error

**Comment by zingale** [comment]
JOSS Review: https://github.com/openjournals/joss-reviews/issues/1636

**Comment by rtfisher** [comment]
I confirm this is still an issue.

**Comment by zingale** [comment]
this change looks good
